routes/web.php
<?php

use App\Pegawai;
use App\TemplateSurat;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/hash', function () {
    $pw = Hash::make('password');
    return $pw;
});
// Route::livewire('/', 'home');

Route::livewire('/profile/{user}', 'profile.profile-index')->name('profile')->middleware('can:onlyUser,user');
Route::get('download/{pegawai}/{folder}/{file}', 'PegawaiController@download')->middleware('can:isSame,pegawai')->name('download');
Route::get('preview/{pegawai}/{folder}/{file}', 'PegawaiController@preview')->middleware('can:isSame,pegawai')->name('preview');

Route::middleware('auth')->group(function () {
    
    Route::middleware('can:isAdmin')->group(function () {
        Route::livewire('/home', 'home')->name('home');
        Route::livewire('/user', 'user.user-index')->name('user');
        Route::livewire('/pegawai', 'pegawai.pegawai-index')->name('pegawai');
        Route::name('template.surat.')->prefix('template-surat')->group(function () {
            Route::livewire('', 'template-surat.template-surat-index')->name('index');
            Route::livewire('/{templateSurat}', 'template-surat.template-surat-show')->name('show');
        });
        Route::group(['prefix' => 'master-data'], function () {
            Route::livewire('/departemen', 'master-data.departemen-index')->name('departemen');
            Route::livewire('/hubungan', 'master-data.hubungan-index')->name('hubungan');
            Route::livewire('/jabatan', 'master-data.jabatan-index')->name('jabatan');
            Route::livewire('/pekerjaan', 'master-data.pekerjaan-index')->name('pekerjaan');
            Route::livewire('/pendidikan', 'master-data.pendidikan-index')->name('pendidikan');
            Route::livewire('/bank', 'master-data.rekening-index')->name('bank');
            Route::livewire('/status-kepegawaian', 'master-data.status-kepegawaian-index')->name('status.kepegawaian');
            Route::livewire('/status-perkawinan', 'master-data.status-perkawinan-index')->name('status.perkawinan');
        });
        Route::get('/export', 'PegawaiController@export')->name('export');
        Route::get('/import/{file}', 'PegawaiController@import')->name('import');
    });
    Route::middleware('can:isSame,pegawai')->prefix('pegawai')->name('pegawai.')->group(function () {
        Route::livewire('/create', 'pegawai.pegawai-create')->name('create')->middleware('can:isAdmin');
        Route::livewire('/update/{pegawai}', 'pegawai.pegawai-update')->name('update');
        Route::livewire('/{pegawai}', 'pegawai.pegawai-show')->name('show');
        Route::get('print/{pegawai}', 'PegawaiController@print')->name('print');
        Route::get('print-surat/{pegawai}/{penomoran}/{jenis}', 'PegawaiController@printLetter')->name('print.letter');
    });
    Route::middleware('can:isSame,pegawai')->prefix('pegawai/{pegawai}/keluarga')->name('keluarga.')->group(function () {
        Route::livewire('/create', 'keluarga.keluarga-create')->name('create');
        Route::livewire('/update/{keluarga}', 'keluarga.keluarga-update')->name('update');
        Route::livewire('/{keluarga}', 'keluarga.keluarga-show')->name('show');
    });

});

Route::get('getdatapegawai', [
    'uses'=>'PegawaiController@getDataPegawai',
    'as'=>'ajax.get.data.pegawai',
]);

Auth::routes();

Route::get('lojot', function(){
    return view('pegawai');
});
Route::get('printes', function(){
    $template = TemplateSurat::findOrFail(1);
    $header = $template->header;
    $main = $template->main;
    $footer = $template->footer;

    return view('surat-ket-bekerja', [
        'header' => $header,
        'main' => $main,
        'footer' => $footer,
        'penomoran' => '001',
        'bulan' => '12',
        'tahun' => '2021',
        'nama' => 'Hans',
        'ttl' => 'Jakarta, 14 Mei 1999',
        'alamat' => 'Jalan pedurungan raya sari no 99',
        'tgl_mulai' => '12 Maret 2017',
        'tgl_brkhr' => '30 Desember 2020',
        'jabatan' => 'Manager',
        'hari_ini' => '11 Januari 2021',
    ]);   
});

Route::get('ori', function()
{
    return view('surat-testing');
});

app/Http/Livewire/Footer.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Footer extends Component
{
    public function render()
    {
        return view('livewire.footer');
    }
}

app/Http/Livewire/Home.php
<?php

namespace App\Http\Livewire;

use Carbon\Carbon;
use Carbon\CarbonImmutable;
use App\Pegawai;
use Livewire\Component;

class Home extends Component
{
    public function render()
    {
        $now = CarbonImmutable::now()->isoFormat('dddd, D MMMM Y');
        $thisMonth = Carbon::now()->isoFormat('MM');
        // dd($thisMonth);
        $birthThisMonth = Pegawai::whereMonth('tanggal_lahir', $thisMonth)->orderBy('nama')->get();
        return view('livewire.home', compact('now', 'birthThisMonth'));
    }
}

app/Http/Livewire/ImportModal.php
<?php

namespace App\Http\Livewire;

use App\Imports\PegawaiImport;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Livewire\Component;
use Livewire\WithFileUploads;
use Maatwebsite\Excel\Facades\Excel;

class ImportModal extends Component
{
    use WithFileUploads;

    public $file;

    public function render()
    {
        return view('livewire.import-modal');
    }

    // public function updated($field)
    // {
    //     $this->validateOnly($field, [
    //         'file'=> 'required|mimes:xlsx,doc,docx,ppt,pptx,ods,odt,odp',
    //     ]);
    // }

    public function import() 
    {
        $validator = Validator::make(
            [
                'file'      => $this->file,
                'extension' => strtolower($this->file->getClientOriginalExtension()),
            ],
            [
                'file'          => 'required',
                'extension'      => 'required|in:doc,csv,xlsx,xls,docx,ppt,odt,ods,odp',
            ]
        );
        // dd(Storage::path('temp/importpegawai.xlsx'))
        $this->deleteFileExist('temp/importpegawai.xlsx');
        $excel = $this->file->storeAs('temp', 'importpegawai.'.$this->file->getClientOriginalExtension());
        $file_path = Storage::path($excel);
        Excel::import(new PegawaiImport, $file_path);
        // (new PegawaiImport)->import('temp/importpegawai.xlsx', 'public', \Maatwebsite\Excel\Excel::XLSX);
        $this->emit('closeModal');
        redirect()->route('pegawai');
    }

    private function deleteFileExist($data)
    {
        $dataCheck = Storage::exists($data);
        // dd($dataCheck);
        if ($dataCheck) {
            Storage::delete($data);
        }
    }
}

app/Http/Livewire/Keluarga/KeluargaCreate.php
<?php

namespace App\Http\Livewire\Keluarga;

use App\Hubungan;
use Livewire\Component;
use Livewire\WithFileUploads;
use App\keluarga;
use App\Pegawai;
use App\Pekerjaan;
use Illuminate\Validation\Rule;

class KeluargaCreate extends Component
{
    
    use WithFileUploads;

    public $pegawai;
    public $nik;
    public $nama;
    public $tempat_lahir;
    public $tanggal_lahir;
    public $jenis_kelamin;
    public $alamat;
    public $agama;
    public $pekerjaan_id;
    public $hubungan_id;

    public function mount(Pegawai $pegawai)
    {
        $this->pegawai = $pegawai;
    }

    public function render()
    {
        $daftar_hubungan = Hubungan::all();
        $daftar_pekerjaan = Pekerjaan::all();
        return view('livewire.keluarga.keluarga-create', compact('daftar_hubungan', 'daftar_pekerjaan'));
    }

    public function updated($field)
    {
        $this->validateOnly($field, [
            'nik'=> ['required', 'numeric', Rule::unique('keluarga')->whereNull('deleted_at'), Rule::unique('pegawai')->whereNull('deleted_at')],
            'nama' => 'required|min:3',
            'tempat_lahir'=> 'required',
            'tanggal_lahir'=> 'required',
            'jenis_kelamin'=> 'required',
            'alamat'=> 'required',
            'agama'=> 'required',
            'pekerjaan_id'=> 'required',
            'hubungan_id'=> 'required',
        ]);
    }

    public function storeKeluarga()
    {
        $validatedData = array_merge(['pegawai_id' => $this->pegawai->id], $this->validate([
            'nik'=> ['required', 'numeric', Rule::unique('keluarga')->whereNull('deleted_at'), Rule::unique('pegawai')->whereNull('deleted_at')],
            'nama' => 'required|min:3',
            'tempat_lahir'=> 'required',
            'tanggal_lahir'=> 'required',
            'jenis_kelamin'=> 'required',
            'alamat'=> 'required',
            'agama'=> 'required',
            'pekerjaan_id'=> 'required',
            'hubungan_id'=> 'required',
        ]));
        $keluarga = keluarga::create($validatedData);
        
        session()->flash('keluarga', 'Keluarga Berhasil Ditambahkan!');
        $url = route('pegawai.show', [$this->pegawai]).'#keluarga';
        redirect()->to($url);
    }
}

app/Http/Livewire/Keluarga/KeluargaShow.php
<?php

namespace App\Http\Livewire\Keluarga;

use Livewire\Component;
use App\keluarga;
use App\pegawai;

class KeluargaShow extends Component
{
    
    public $pegawai;
    public $keluarga;
    public $showKeluarga = false;
    public $createKeluarga = false; 
    public $updateKeluarga = false; 
    public $conf; 
    
    protected $listeners = [
    ];
    
    public function mount(Pegawai $pegawai, Keluarga $keluarga)
    {
        $this->pegawai = $pegawai;
        $this->keluarga = $keluarga;
        // dd($pegawai);
    }
    
    public function render()
    {
        $pegawai = $this->pegawai;
        $keluarga = $this->keluarga;
        // // dd($keluarga);
        return view('livewire.keluarga.keluarga-show', compact('keluarga', 'pegawai'));
    }
    
    public function destroy($conf)
    {
        if($conf){
            $this->keluarga->delete();
            
            session()->flash('keluarga', 'Data keluarga berhasil dihapus!');
            $url = route('pegawai.show', [$this->pegawai]).'#keluarga';
            redirect()->to($url);
        }
    }

    public function message()
    {
        session()->flash('pesan', 'Data keluarga telah ditambahkan');
    }
}

app/Http/Livewire/Keluarga/KeluargaUpdate.php
<?php

namespace App\Http\Livewire\Keluarga;

use App\Hubungan;
use Livewire\Component;
use Livewire\WithFileUploads;
use App\keluarga;
use App\Pegawai;
use App\Pekerjaan;
use Illuminate\Validation\Rule;

class KeluargaUpdate extends Component
{
    
    use WithFileUploads;
    public $pegawai;
    public $keluarga;
    public $nik;
    public $nama;
    public $tempat_lahir;
    public $tanggal_lahir;
    public $jenis_kelamin;
    public $alamat;
    public $agama;
    public $pekerjaan_id;
    public $hubungan_id;

    protected $listeners = [
    ];

    public function mount(Pegawai $pegawai, Keluarga $keluarga)
    {
        $this->pegawai = $pegawai;
        $this->keluarga = $keluarga;
        $this->showKeluarga($keluarga);
        // dd($this->pekerjaan_id);
    }

    public function render()
    {
        $daftar_hubungan = Hubungan::all();
        $daftar_pekerjaan = Pekerjaan::all();
        return view('livewire.keluarga.keluarga-update', compact('daftar_hubungan', 'daftar_pekerjaan'));
    }

    public function showKeluarga($keluarga)
    {
        $this->nik = $keluarga['nik'];
        $this->nama = $keluarga['nama'];
        $this->tempat_lahir = $keluarga['tempat_lahir'];
        $this->tanggal_lahir = $keluarga['tanggal_lahir'];
        $this->jenis_kelamin = $keluarga['jenis_kelamin'];
        $this->alamat = $keluarga['alamat'];
        $this->agama = $keluarga['agama'];
        $this->pekerjaan_id = $keluarga['pekerjaan_id'];
        $this->hubungan_id = $keluarga['hubungan_id'];
    }

    public function updated($field)
    {
        $this->validateOnly($field, [
            'nik'=> ['required', 'numeric', Rule::unique('pegawai')->ignore($this->keluarga)->whereNull('deleted_at'), Rule::unique('keluarga')->ignore($this->keluarga)->whereNull('deleted_at')],
            'nama' => 'required|min:3',
            'tempat_lahir'=> 'required',
            'tanggal_lahir'=> 'required',
            'jenis_kelamin'=> 'required',
            'alamat'=> 'required',
            'agama'=> 'required',
            'pekerjaan_id'=> 'required',
            'hubungan_id'=> 'required',
        ]);
    }

    public function update()
    {
        $validatedData = $this->validate([
            'nik'=> 'required',
            'nama' => 'required|min:3',
            'tempat_lahir'=> 'required',
            'tanggal_lahir'=> 'required',
            'jenis_kelamin'=> 'required',
            'alamat'=> 'required',
            'agama'=> 'required',
            'pekerjaan_id'=> 'required',
            'hubungan_id'=> 'required',
        ]);
        if ( $this->keluarga->id ) {
            $validatedData = array_merge(['pegawai_id' => $this->pegawai->id,], $validatedData);
            $keluarga = keluarga::find($this->keluarga->id);
            $keluarga->update($validatedData);

            session()->flash('pesan', 'Keluarga Berhasil Diupdate!');
            $url = route('keluarga.show', [$this->pegawai, $this->keluarga]);
            redirect()->to($url);
        }
    }
}

app/Http/Livewire/MasterData/DepartemenIndex.php
<?php

namespace App\Http\Livewire\MasterData;

use App\Departemen;
use Illuminate\Validation\Rule;
use Livewire\Component;
use Livewire\WithPagination;

class DepartemenIndex extends Component
{
    use WithPagination;
 
    public $statusUpdate = false;
    public $conf;
    public $paginate = 5;
    public $search;
    
    public $nama;
    public $deskripsi;
    public $departemenId;

    // Initialize variable
    public function mount()
    {
    }

    // Where to return the view
    public function render()
    {
        return view('livewire.master-data.departemen-index', [
            'daftar_departemen' => $this->search === null ?
            Departemen::latest()->paginate($this->paginate) :
            Departemen::latest()->where('nama', env('DB_CONNECTION') == 'pgsql' ? 'ilike' : 'like', '%' . $this->search . '%')
            ->orWhere('deskripsi', env('DB_CONNECTION') == 'pgsql' ? 'ilike' : 'like', '%' . $this->search . '%')
            ->paginate($this->paginate)
        ]);
    }

    // Realtime validation
    public function updated($field)
    {
        $this->validateOnly($field, [
            'nama' => ['required', Rule::unique('departemen')->ignore($this->departemenId)],
            'deskripsi' => 'required',
        ]);
    }

    // Function to check it's update or create
    public function submit()
    {
        $validatedData = $this->validate([
            'nama' => ['required', Rule::unique('departemen')->ignore($this->departemenId)],
            'deskripsi' => 'required',
        ]);

        if ($this->statusUpdate && $this->departemenId) {
            $this->update($validatedData);
            session()->flash('pesan', 'Departemen '.$this->nama.' telah tersimpan!');
        } else {
            $this->store($validatedData);
            session()->flash('pesan', 'Departemen '.$this->nama.' telah ditambahkan!');
        };
        redirect()->route('departemen');
    }

    // Create departemen
    public function store($validatedData)
    {
        // $validatedData = array_merge($validatedData, ['password' =>Hash::make('password')]);
        $departemen = Departemen::create($validatedData);
    }

    // Show departemen data to form
    public function showDepartemen($id)
    {
        $this->statusUpdate = true;
        $departemen = Departemen::find($id);
        $this->nama = $departemen['nama'];
        $this->deskripsi = $departemen['deskripsi'];
        $this->departemenId = $departemen['id'];
    }

    // Update departemen
    public function update($validatedData)
    {
        $departemen = Departemen::find($this->departemenId);
        $departemen->update($validatedData);
    }

    // Delete departemen
    public function destroy($id, $conf)
    {
        if($id && $conf){
            $data = Departemen::find($id);
            $data->delete();
            session()->flash('pesan', 'Departemen berhasil dihapus!');
        }
        redirect()->route('departemen');
    }
}

app/Http/Livewire/Navigate.php
<?php

namespace App\Http\Livewire;

use App\Pegawai;
use App\User;
use Illuminate\Support\Facades\Http;
use Livewire\Component;
use Illuminate\Support\Str;

class Navigate extends Component
{
    public $src_foto; 
    public $response; 
    public $user; 
    public $pegawai; 

    protected $listeners = [
        'updatedFoto' => 'handleUpFoto'
    ];

    public function mount($user)
    {
        $this->user = $user;
        $this->pegawai = $user->pegawai;
        if (isset($this->pegawai->foto_profil)) {
            $this->src_foto = route('preview', [
                'pegawai' => $this->pegawai,
                'folder' => Str::before($this->pegawai->foto_profil, '/'),
                'file' => Str::after($this->pegawai->foto_profil, '/')
            ]);
            $this->response = Http::get($this->src_foto)->successful();
        }

    }

    public function handleUpFoto($src_foto, $response)
    {
        $this->src_foto = $src_foto;
        $this->response = $response;
    }

    public function render()
    {
        return view('livewire.navigate');
    }
}

resources/views/livewire/keluarga/keluarga-show.blade.php
@section('title', 'Detail Keluarga')

@section('header', 'Detail Keluarga')

@section('breadcumb')
    @can('isAdmin')
        <li class="breadcrumb-item"><a href="{{route('home')}}"><i class="fa fa-home" aria-hidden="true"></i>                    </a></li>
        <li class="breadcrumb-item"><a href="{{route('pegawai')}}">Pegawai</a></li>
    @endcan
    <li class="breadcrumb-item"><a href="{{route('pegawai.show', $pegawai)}}">Detail Pegawai</a></li>
    <li class="breadcrumb-item active">Detail Keluarga</li>
@endsection

{{-- content --}}
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Detail Keluarga</h3>
        <div class="card-tools">
            <a href="{{route('keluarga.update', [$pegawai, $keluarga])}}" class="btn btn-sm btn-success"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>
            </a>
            <button data-toggle="modal" data-target="#deletemodal{{$keluarga->id}}" class="btn btn-sm btn-danger">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
            </button>
            <div class="modal fade" id="deletemodal{{$keluarga->id}}" tabindex="-1" aria-labelledby="deletemodalModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-md">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deletemodalModalLabel">Konfirmasi</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Apakah anda yakin?
                        </div>
                        <div class="modal-footer">
                            <button type="button" wire:click="destroy(true)" class="btn btn-danger" data-dismiss="modal">Hapus</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body"> 
        @if (session()->has('pesan'))
        <div class="alert alert-success">
            {{ session('pesan') }}
        </div>
        @endif
        {{-- {{ dd($keluarga) }} --}}
        <table class="table table-borderless ">
            <tbody>
                {{-- {{dd($keluarga->nik)}} --}}
                <tr>
                    <td style="width: 18%">NIK</td>
                    <td>: {{ $keluarga->nik }}</td>
                </tr>
                <tr>
                    <td>Nama Pegawai</td>
                    <td>: {{ $keluarga->nama }}</td>
                </tr>
                <tr>
                    <td>Tempat & Tanggal Lahir</td>
                    <td class="text-capitalize">: {{ $keluarga->tempat_lahir }}, {{ \Carbon\Carbon::createFromFormat('d/m/Y', $keluarga->tanggal_lahir)->isoFormat('D MMMM Y') }}</td>
                </tr>
                <tr>
                    <td>Jenis Kelamin</td>
                    <td>: {{ $keluarga->jenis_kelamin }}</td>
                </tr>
                <tr>
                    <td>Alamat</td>
                    <td>: {{ $keluarga->alamat }}</td>
                </tr>
                <tr>
                    <td>Agama</td>
                    <td>: {{ $keluarga->agama }}</td>
                </tr>
                <tr>
                    <td>Pekerjaan</td>
                    <td>: {{ $keluarga->pekerjaan->nama }}</td>
                </tr>
                <tr>
                    <td>Hubungan</td>
                    <td>: {{ $keluarga->hubungan->nama }}</td>    
                </tr>
            </tbody>
        </table>
    </div>
</div>
{{-- ./content --}}