routes/web.php
<?php

use App\Pegawai;
use App\TemplateSurat;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/hash', function () {
    $pw = Hash::make('password');
    return $pw;
});
// Route::livewire('/', 'home');

Route::livewire('/profile/{user}', 'profile.profile-index')->name('profile')->middleware('can:onlyUser,user');
Route::get('download/{pegawai}/{folder}/{file}', 'PegawaiController@download')->middleware('can:isSame,pegawai')->name('download');
Route::get('preview/{pegawai}/{folder}/{file}', 'PegawaiController@preview')->middleware('can:isSame,pegawai')->name('preview');

Route::middleware('auth')->group(function () {
    
    Route::middleware('can:isAdmin')->group(function () {
        Route::livewire('/home', 'home')->name('home');
        Route::livewire('/user', 'user.user-index')->name('user');
        Route::livewire('/pegawai', 'pegawai.pegawai-index')->name('pegawai');
        Route::name('template.surat.')->prefix('template-surat')->group(function () {
            Route::livewire('', 'template-surat.template-surat-index')->name('index');
            Route::livewire('/{templateSurat}', 'template-surat.template-surat-show')->name('show');
        });
        Route::group(['prefix' => 'master-data'], function () {
            Route::livewire('/departemen', 'master-data.departemen-index')->name('departemen');
            Route::livewire('/hubungan', 'master-data.hubungan-index')->name('hubungan');
            Route::livewire('/jabatan', 'master-data.jabatan-index')->name('jabatan');
            Route::livewire('/pekerjaan', 'master-data.pekerjaan-index')->name('pekerjaan');
            Route::livewire('/pendidikan', 'master-data.pendidikan-index')->name('pendidikan');
            Route::livewire('/bank', 'master-data.rekening-index')->name('bank');
            Route::livewire('/status-kepegawaian', 'master-data.status-kepegawaian-index')->name('status.kepegawaian');
            Route::livewire('/status-perkawinan', 'master-data.status-perkawinan-index')->name('status.perkawinan');
        });
        Route::get('/export', 'PegawaiController@export')->name('export');
        Route::get('/import/{file}', 'PegawaiController@import')->name('import');
    });
    Route::middleware('can:isSame,pegawai')->prefix('pegawai')->name('pegawai.')->group(function () {
        Route::livewire('/create', 'pegawai.pegawai-create')->name('create')->middleware('can:isAdmin');
        Route::livewire('/update/{pegawai}', 'pegawai.pegawai-update')->name('update');
        Route::livewire('/{pegawai}', 'pegawai.pegawai-show')->name('show');
        Route::get('print/{pegawai}', 'PegawaiController@print')->name('print');
        Route::get('print-surat/{pegawai}/{penomoran}/{jenis}', 'PegawaiController@printLetter')->name('print.letter');
    });
    Route::middleware('can:isSame,pegawai')->prefix('pegawai/{pegawai}/keluarga')->name('keluarga.')->group(function () {
        Route::livewire('/create', 'keluarga.keluarga-create')->name('create');
        Route::livewire('/update/{keluarga}', 'keluarga.keluarga-update')->name('update');
        Route::livewire('/{keluarga}', 'keluarga.keluarga-show')->name('show');
    });

});

Route::get('getdatapegawai', [
    'uses'=>'PegawaiController@getDataPegawai',
    'as'=>'ajax.get.data.pegawai',
]);

Auth::routes();

Route::get('lojot', function(){
    return view('pegawai');
});
Route::get('printes', function(){
    $template = TemplateSurat::findOrFail(1);
    $header = $template->header;
    $main = $template->main;
    $footer = $template->footer;

    return view('surat-ket-bekerja', [
        'header' => $header,
        'main' => $main,
        'footer' => $footer,
        'penomoran' => '001',
        'bulan' => '12',
        'tahun' => '2021',
        'nama' => 'Hans',
        'ttl' => 'Jakarta, 14 Mei 1999',
        'alamat' => 'Jalan pedurungan raya sari no 99',
        'tgl_mulai' => '12 Maret 2017',
        'tgl_brkhr' => '30 Desember 2020',
        'jabatan' => 'Manager',
        'hari_ini' => '11 Januari 2021',
    ]);   
});

Route::get('ori', function()
{
    return view('surat-testing');
});

app/Http/Controllers/PegawaiController.php
<?php

namespace App\Http\Controllers;

use App\Exports\PegawaiExport;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Http\Request;
use App\{Pegawai, Jabatan, StatusKepegawaian, TemplateSurat};
use App\Imports\PegawaiImport;
use PDF;
use DataTables;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;

class PegawaiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view ('pegawai');
    }

    public function getDataPegawai()
    {
        $pegawai = Pegawai::with('jabatan');
        // $DataTables = ;
        return DataTables::eloquent($pegawai)
                    ->editColumn('jabatan_id', function(Pegawai $pegawai) {
                        return $pegawai->jabatan->nama;
                    })
                    ->addColumn('aksi', function($p) {
                        $link = route('pegawai.show', ['pegawai' => $p]);
                        return '<a href="'. $link .'" class="btn btn-info btn-sm text-white" data-turbolinks-action="replace" >Detail</a>';
                    })
                    ->filter(function ($query) {
                        if (request()->has('status')) {
                            $query->where('status', 'like', "%" . request('status') . "%");
                        }
                    }, true)
                    ->rawColumns(['aksi'])
                    ->addIndexColumn()
                    ->toJson();
    }

    public function print($pegawai)
    {
        $pegawai = Pegawai::where('nip', $pegawai)->firstOrFail();
        $pdf = PDF::loadView('livewire.pegawai.pegawai-print', ['pegawai' => $pegawai]);
        return $pdf->stream('CV '.$pegawai->nama.'-'.$pegawai->nip.'.pdf');
    }

    public function printLetter($pegawai, $penomoran, $jenis)
    {
        $pegawai = Pegawai::where('nip', $pegawai)->firstOrFail();
        $jenis = StatusKepegawaian::findOrFail($jenis)->id;
        $collection = collect($pegawai->statusKepegawaian)->map(function($statpeg) {
            return $statpeg;
        });
        $stat_kep = $collection->where('id', $jenis)->first();
        $rome_month = [
            1 => 'I',
            2 => 'II',
            3 => 'III',
            4 => 'IV',
            5 => 'V',
            6 => 'VI',
            7 => 'VII',
            8 => 'VIII',
            9 => 'IX',
            10 => 'X',
            11 => 'XI',
            12 => 'XII',
        ];
        $month = $rome_month[date('n')];
        $template = TemplateSurat::where('status_kepegawaian_id', $jenis)->first();
        $header = $template->header;
        $main = json_decode($template->main);
        $footer = $template->footer;

        $pdf = PDF::loadView('surat-ket-bekerja', [
            'pegawai' => $pegawai,
            'stat_kep' => $stat_kep,
            'jenis' => $jenis,
            'header' => $header,
            'footer' => $footer,
            'main' => $main,
            'month' => $month,
            'penomoran' => $penomoran,
            ]);
        return $pdf->stream('Surat Keterangan Kerja.pdf');
    }

    public function export()
    {
        return Excel::download(new PegawaiExport, 'pegawai.xlsx');
    }

    public function import($file)
    {
        Excel::import(new PegawaiImport, $file);
        return redirect()->route('pegawai')->with('pesan', 'All good!');
    }

    public function download($pegawai, $folder, $file)
    {
        $pegawai = Pegawai::where('nip', $pegawai)->firstOrFail();
        $filename = $folder.'-'.$pegawai->nama.'.'.\File::extension($file);
        return response()->download(Storage::path($folder.'/'.$file), $filename);
    }

    public function preview($pegawai, $folder, $file)
    {
        $path = Storage::path($folder.'/'.$file);
        return response()->file($path);;
    }
}

app/Http/Livewire/Footer.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Footer extends Component
{
    public function render()
    {
        return view('livewire.footer');
    }
}

app/Http/Livewire/Home.php
<?php

namespace App\Http\Livewire;

use Carbon\Carbon;
use Carbon\CarbonImmutable;
use App\Pegawai;
use Livewire\Component;

class Home extends Component
{
    public function render()
    {
        $now = CarbonImmutable::now()->isoFormat('dddd, D MMMM Y');
        $thisMonth = Carbon::now()->isoFormat('MM');
        // dd($thisMonth);
        $birthThisMonth = Pegawai::whereMonth('tanggal_lahir', $thisMonth)->orderBy('nama')->get();
        return view('livewire.home', compact('now', 'birthThisMonth'));
    }
}

app/Http/Livewire/ImportModal.php
<?php

namespace App\Http\Livewire;

use App\Imports\PegawaiImport;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Livewire\Component;
use Livewire\WithFileUploads;
use Maatwebsite\Excel\Facades\Excel;

class ImportModal extends Component
{
    use WithFileUploads;

    public $file;

    public function render()
    {
        return view('livewire.import-modal');
    }

    // public function updated($field)
    // {
    //     $this->validateOnly($field, [
    //         'file'=> 'required|mimes:xlsx,doc,docx,ppt,pptx,ods,odt,odp',
    //     ]);
    // }

    public function import() 
    {
        $validator = Validator::make(
            [
                'file'      => $this->file,
                'extension' => strtolower($this->file->getClientOriginalExtension()),
            ],
            [
                'file'          => 'required',
                'extension'      => 'required|in:doc,csv,xlsx,xls,docx,ppt,odt,ods,odp',
            ]
        );
        // dd(Storage::path('temp/importpegawai.xlsx'))
        $this->deleteFileExist('temp/importpegawai.xlsx');
        $excel = $this->file->storeAs('temp', 'importpegawai.'.$this->file->getClientOriginalExtension());
        $file_path = Storage::path($excel);
        Excel::import(new PegawaiImport, $file_path);
        // (new PegawaiImport)->import('temp/importpegawai.xlsx', 'public', \Maatwebsite\Excel\Excel::XLSX);
        $this->emit('closeModal');
        redirect()->route('pegawai');
    }

    private function deleteFileExist($data)
    {
        $dataCheck = Storage::exists($data);
        // dd($dataCheck);
        if ($dataCheck) {
            Storage::delete($data);
        }
    }
}

app/Http/Livewire/Keluarga/KeluargaCreate.php
<?php

namespace App\Http\Livewire\Keluarga;

use App\Hubungan;
use Livewire\Component;
use Livewire\WithFileUploads;
use App\keluarga;
use App\Pegawai;
use App\Pekerjaan;
use Illuminate\Validation\Rule;

class KeluargaCreate extends Component
{
    
    use WithFileUploads;

    public $pegawai;
    public $nik;
    public $nama;
    public $tempat_lahir;
    public $tanggal_lahir;
    public $jenis_kelamin;
    public $alamat;
    public $agama;
    public $pekerjaan_id;
    public $hubungan_id;

    public function mount(Pegawai $pegawai)
    {
        $this->pegawai = $pegawai;
    }

    public function render()
    {
        $daftar_hubungan = Hubungan::all();
        $daftar_pekerjaan = Pekerjaan::all();
        return view('livewire.keluarga.keluarga-create', compact('daftar_hubungan', 'daftar_pekerjaan'));
    }

    public function updated($field)
    {
        $this->validateOnly($field, [
            'nik'=> ['required', 'numeric', Rule::unique('keluarga')->whereNull('deleted_at'), Rule::unique('pegawai')->whereNull('deleted_at')],
            'nama' => 'required|min:3',
            'tempat_lahir'=> 'required',
            'tanggal_lahir'=> 'required',
            'jenis_kelamin'=> 'required',
            'alamat'=> 'required',
            'agama'=> 'required',
            'pekerjaan_id'=> 'required',
            'hubungan_id'=> 'required',
        ]);
    }

    public function storeKeluarga()
    {
        $validatedData = array_merge(['pegawai_id' => $this->pegawai->id], $this->validate([
            'nik'=> ['required', 'numeric', Rule::unique('keluarga')->whereNull('deleted_at'), Rule::unique('pegawai')->whereNull('deleted_at')],
            'nama' => 'required|min:3',
            'tempat_lahir'=> 'required',
            'tanggal_lahir'=> 'required',
            'jenis_kelamin'=> 'required',
            'alamat'=> 'required',
            'agama'=> 'required',
            'pekerjaan_id'=> 'required',
            'hubungan_id'=> 'required',
        ]));
        $keluarga = keluarga::create($validatedData);
        
        session()->flash('keluarga', 'Keluarga Berhasil Ditambahkan!');
        $url = route('pegawai.show', [$this->pegawai]).'#keluarga';
        redirect()->to($url);
    }
}

app/Http/Livewire/Keluarga/KeluargaShow.php
<?php

namespace App\Http\Livewire\Keluarga;

use Livewire\Component;
use App\keluarga;
use App\pegawai;

class KeluargaShow extends Component
{
    
    public $pegawai;
    public $keluarga;
    public $showKeluarga = false;
    public $createKeluarga = false; 
    public $updateKeluarga = false; 
    public $conf; 
    
    protected $listeners = [
    ];
    
    public function mount(Pegawai $pegawai, Keluarga $keluarga)
    {
        $this->pegawai = $pegawai;
        $this->keluarga = $keluarga;
        // dd($pegawai);
    }
    
    public function render()
    {
        $pegawai = $this->pegawai;
        $keluarga = $this->keluarga;
        // // dd($keluarga);
        return view('livewire.keluarga.keluarga-show', compact('keluarga', 'pegawai'));
    }
    
    public function destroy($conf)
    {
        if($conf){
            $this->keluarga->delete();
            
            session()->flash('keluarga', 'Data keluarga berhasil dihapus!');
            $url = route('pegawai.show', [$this->pegawai]).'#keluarga';
            redirect()->to($url);
        }
    }

    public function message()
    {
        session()->flash('pesan', 'Data keluarga telah ditambahkan');
    }
}

app/Http/Livewire/Keluarga/KeluargaUpdate.php
<?php

namespace App\Http\Livewire\Keluarga;

use App\Hubungan;
use Livewire\Component;
use Livewire\WithFileUploads;
use App\keluarga;
use App\Pegawai;
use App\Pekerjaan;
use Illuminate\Validation\Rule;

class KeluargaUpdate extends Component
{
    
    use WithFileUploads;
    public $pegawai;
    public $keluarga;
    public $nik;
    public $nama;
    public $tempat_lahir;
    public $tanggal_lahir;
    public $jenis_kelamin;
    public $alamat;
    public $agama;
    public $pekerjaan_id;
    public $hubungan_id;

    protected $listeners = [
    ];

    public function mount(Pegawai $pegawai, Keluarga $keluarga)
    {
        $this->pegawai = $pegawai;
        $this->keluarga = $keluarga;
        $this->showKeluarga($keluarga);
        // dd($this->pekerjaan_id);
    }

    public function render()
    {
        $daftar_hubungan = Hubungan::all();
        $daftar_pekerjaan = Pekerjaan::all();
        return view('livewire.keluarga.keluarga-update', compact('daftar_hubungan', 'daftar_pekerjaan'));
    }

    public function showKeluarga($keluarga)
    {
        $this->nik = $keluarga['nik'];
        $this->nama = $keluarga['nama'];
        $this->tempat_lahir = $keluarga['tempat_lahir'];
        $this->tanggal_lahir = $keluarga['tanggal_lahir'];
        $this->jenis_kelamin = $keluarga['jenis_kelamin'];
        $this->alamat = $keluarga['alamat'];
        $this->agama = $keluarga['agama'];
        $this->pekerjaan_id = $keluarga['pekerjaan_id'];
        $this->hubungan_id = $keluarga['hubungan_id'];
    }

    public function updated($field)
    {
        $this->validateOnly($field, [
            'nik'=> ['required', 'numeric', Rule::unique('pegawai')->ignore($this->keluarga)->whereNull('deleted_at'), Rule::unique('keluarga')->ignore($this->keluarga)->whereNull('deleted_at')],
            'nama' => 'required|min:3',
            'tempat_lahir'=> 'required',
            'tanggal_lahir'=> 'required',
            'jenis_kelamin'=> 'required',
            'alamat'=> 'required',
            'agama'=> 'required',
            'pekerjaan_id'=> 'required',
            'hubungan_id'=> 'required',
        ]);
    }

    public function update()
    {
        $validatedData = $this->validate([
            'nik'=> 'required',
            'nama' => 'required|min:3',
            'tempat_lahir'=> 'required',
            'tanggal_lahir'=> 'required',
            'jenis_kelamin'=> 'required',
            'alamat'=> 'required',
            'agama'=> 'required',
            'pekerjaan_id'=> 'required',
            'hubungan_id'=> 'required',
        ]);
        if ( $this->keluarga->id ) {
            $validatedData = array_merge(['pegawai_id' => $this->pegawai->id,], $validatedData);
            $keluarga = keluarga::find($this->keluarga->id);
            $keluarga->update($validatedData);

            session()->flash('pesan', 'Keluarga Berhasil Diupdate!');
            $url = route('keluarga.show', [$this->pegawai, $this->keluarga]);
            redirect()->to($url);
        }
    }
}

resources/views/livewire/pegawai/pegawai-index.blade.php
@section('title', 'Pegawai')

@section('header', 'Daftar Pegawai')

@section('breadcumb')
    <li class="breadcrumb-item"><a href="{{route('home')}}"><i class="fa fa-home" aria-hidden="true"></i>                    </a></li>
    <li class="breadcrumb-item"><a href="{{route('pegawai')}}">Pegawai</a></li>
    <li class="breadcrumb-item active">Daftar Pegawai</li>
@endsection

{{-- content --}}
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Daftar Pegawai</h3>
            <div class="card-tools">
                @auth
                <livewire:import-modal key="'importExcelModal'">
                <a href="{{route('export')}}" target="_blank" wire:click="export" class="btn btn-sm btn-success" style=""><i class="fa fa-file-excel-o" aria-hidden="true"></i>export</a>
                <a href="{{ route('pegawai.create') }}" class="btn btn-sm btn-primary"><i class="fa fa-plus-square" aria-hidden="true"></i> Tambah Pegawai</a>
                @endauth
            </div>
        </div>
        <div class="card-body">
            @if (session()->has('pesan'))
            <div class="alert alert-success" id="pesan"> 
                {{ session('pesan') }}
            </div>
            @elseif (session()->has('pesan-error'))
            <div class="alert alert-danger" id="pesan"> 
                {{ session('pesan-error') }}
            </div>
            @endif
            
            <div wire:ignore wire:key="pegtabell">
                <table class="table table-bordered table-responsive-md table-hover mx-auto" id="pegtable" width="100%">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nama</th>
                            <th scope="col">NIP</th>
                            <th scope="col">Jabatan</th>
                            <th scope="col">Aksi</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->  
{{-- /.content --}}

@push('scripts')
<script type="application/javascript">
        $(document).ready(function(){
            jQuery.noConflict();
            livewire.on('notified', () => {
                $(".alert").fadeTo(5000, 500).slideUp(500, function(){
                    $(".alert").slideUp(500);
                });
            });
            // const comp = @th;
            document.querySelector('#pegtable');
            let pegtable =  $('#pegtable').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                stateSave: true,
                order: [[1,'asc']],
                ajax: '{{ route('ajax.get.data.pegawai') }}',
                columns: [
                    { data: 'DT_RowIndex', class: 'text-center', width: '20px', orderable: false, searchable: false },                    
                    { data: 'nama', name: 'nama', width: '250px' },
                    { data: 'nip', name: 'nip', width: '200px' },
                    { data: 'jabatan_id', name: 'jabatan_id', class: 'text-center', width: '100px' },
                    { data: 'aksi', name: 'aksi', orderable: false, searchable: false, class: 'text-center', width: '50px' },
                    
                ],
                // "dom": '<"toolbar">frtip',
                // fnInitComplete: function(){
                // $('div.toolbar').html('<a href="{{route('export')}}" target="_blank" wire:click="export" class="btn btn btn-light mb-2" style=""><strong class="">Export to excel</strong></a>');
                // }
            });

            document.addEventListener("turbolinks:before-cache", function() {
                if (pegtable != null) {
                    pegtable.destroy();
                    pegtable = null;
                }
            });
            
            // document.addEventListener('turbolinks:load', function () {
            //     const dtlength = document.querySelectorAll('.dataTables_length')
            //     if ( dtlength.length != 0) {
            //         while (dtlength.length != 0) {
            //             // element.parentNode.removeChild(element);
            //             console.log(dtlength.length);
            //         }
            //     }
            // });
        });
    </script>
@endpush